// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TDS_CarPark.API.Data;

#nullable disable

namespace TDS_CarPark.API.Migrations
{
    [DbContext(typeof(CarParkDbContext))]
    partial class CarParkDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TDS_CarPark.API.Models.Domain.Space", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsOccupied")
                        .HasColumnType("bit");

                    b.Property<int>("SpaceNumber")
                        .HasColumnType("int");

                    b.Property<DateTime?>("TimeIn")
                        .HasColumnType("datetime2");

                    b.Property<string>("VehicleReg")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("VehicleTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("VehicleTypeId");

                    b.ToTable("Space");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1d4f2e8-1001-4b8a-9b12-444444444441"),
                            IsOccupied = false,
                            SpaceNumber = 1
                        },
                        new
                        {
                            Id = new Guid("a1d4f2e8-1002-4b8a-9b12-444444444442"),
                            IsOccupied = false,
                            SpaceNumber = 2
                        },
                        new
                        {
                            Id = new Guid("a1d4f2e8-1003-4b8a-9b12-444444444443"),
                            IsOccupied = false,
                            SpaceNumber = 3
                        },
                        new
                        {
                            Id = new Guid("a1d4f2e8-1004-4b8a-9b12-444444444444"),
                            IsOccupied = false,
                            SpaceNumber = 4
                        },
                        new
                        {
                            Id = new Guid("a1d4f2e8-1005-4b8a-9b12-444444444445"),
                            IsOccupied = false,
                            SpaceNumber = 5
                        },
                        new
                        {
                            Id = new Guid("a1d4f2e8-1006-4b8a-9b12-444444444446"),
                            IsOccupied = false,
                            SpaceNumber = 6
                        },
                        new
                        {
                            Id = new Guid("a1d4f2e8-1007-4b8a-9b12-444444444447"),
                            IsOccupied = false,
                            SpaceNumber = 7
                        },
                        new
                        {
                            Id = new Guid("a1d4f2e8-1008-4b8a-9b12-444444444448"),
                            IsOccupied = false,
                            SpaceNumber = 8
                        },
                        new
                        {
                            Id = new Guid("a1d4f2e8-1009-4b8a-9b12-444444444449"),
                            IsOccupied = false,
                            SpaceNumber = 9
                        });
                });

            modelBuilder.Entity("TDS_CarPark.API.Models.Domain.VehicleType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Cost")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("VehicleType");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1d4f2e8-0001-4b8a-9b12-111111111111"),
                            Cost = 0.10000000000000001,
                            Name = "Small Car",
                            Number = 1
                        },
                        new
                        {
                            Id = new Guid("a1d4f2e8-0002-4b8a-9b12-222222222222"),
                            Cost = 0.20000000000000001,
                            Name = "Medium Car",
                            Number = 2
                        },
                        new
                        {
                            Id = new Guid("a1d4f2e8-0003-4b8a-9b12-333333333333"),
                            Cost = 0.40000000000000002,
                            Name = "Large Car",
                            Number = 3
                        });
                });

            modelBuilder.Entity("TDS_CarPark.API.Models.Domain.Space", b =>
                {
                    b.HasOne("TDS_CarPark.API.Models.Domain.VehicleType", "VehicleType")
                        .WithMany()
                        .HasForeignKey("VehicleTypeId");

                    b.Navigation("VehicleType");
                });
#pragma warning restore 612, 618
        }
    }
}
